name: "nix flake build nixGLIntel"
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

jobs:
  nix-flake-build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Flake build
      run: |
        nix build .#nixGLIntel

    - name: Formatter check
      run: |
        nix fmt
        git diff --exit-code
